package com.pdd.track.model;

public enum TimeLineDayHintType {
    LECTURE_WITHOUT_STUDY,
    NEEDS_RESTUDY,
    STUDY_WITHOUT_TESTING,
    ADVICE_REFRESH_TESTS,
    LAST_TESTING_IS_RED,
    AVERAGE_TESTS_PERCENTAGE_IS_RED
}
